### ISSUE TITLE
How can I remove this theme?

### ISSUE THREAD

**Issue by tahdiislam** [vinceliuice/WhiteSur-firefox-theme#32] opened 2023-10-16 02:13 UTC

**Comment by AdamXweb** [comment] 2023-10-16 02:45
Duplicate of #29

See https://github.com/vinceliuice/WhiteSur-firefox-theme/issues/29#issuecomment-1702949453

**Comment by tahdiislam** [comment] 2023-10-16 03:37
> Duplicate of #29
> 
> See [#29 (comment)](https://github.com/vinceliuice/WhiteSur-firefox-theme/issues/29#issuecomment-1702949453)

Thanks.

**Closed** 2024-02-28 17:35 UTC
